### ISSUE TITLE
Links throws 404

### ISSUE THREAD

**Issue by ChrisBeeley** [nhs-r-community/NHSR-way#170]
https://github.com/nhs-r-community/NHSR-way/blob/2919a5090bebd554f4cb948432274ef58c9b4248/nhsr-vision.qmd#L31

http://training.nhsrcommunity.com/ throws a 404

**Comment by Lextuga007** [comment]
Looks like there is a duplicate bracket at the end of the url that needs to be removed.  Thanks!

**Comment by ChrisBeeley** [comment]
Not sure it is that, this also throws a 404 https://training.nhsrcommunity.com/

**Comment by ChrisBeeley** [comment]
In fact, now I look, the duplicate bracket is correct, it's in a parenthetical part of the sentence

**Comment by Lextuga007** [comment]
You're right! I hadn't set up a redirect on the domain which was why it was going to a 404. Thanks!
