### ISSUE TITLE
Incorrect link to intro course materials?

### ISSUE THREAD

**Issue by lgs85** [nhs-r-community/NHSR-way#82]
Am I right in thinking that the link to course materials [here](https://github.com/nhs-r-community/NHSR-way/blob/main/training.qmd#L115) should link to [this repo](https://github.com/nhs-r-community/intro-r-rstudio) and not to the older one?

I'm using the latter for the course tomorrow and I think it makes sense to link to the latest version?

**Comment by lgs85** [comment]
(I think I've understood the various repositories now, but it took me a while). I think this can be clarified with two separate links from the above qmd file - one to the latest set of html files, and another to the data repo

**Comment by Lextuga007** [comment]
Thank you for raising the issue 😄 I've updated the section to be, I hope, a little clearer. Thank you for persevering and the update, much appreciated.
